// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drlcflhgzhwxuzqhmdmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybGNmbGhnemh3eHV6cWhtZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzk1MjAsImV4cCI6MjA3MDcxNTUyMH0.Qyg5_k4VRWJyaO7GWPTDDn8bEnVqXPJOWVY9V0NYM9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});